create Employee model with validations
DadaLV/personnel_management pull request #1
Opened 2023-05-10 09:03 UTC by DadaLV

2023-05-10 10:00 UTC, kvasyaa requested changes
cannot see the proper validation errors.
<img width="1675" alt="Знімок екрана 2023-05-10 о 12 59 20" src="https://github.com/DadaLV/personnel_management/assets/83231382/d8f14416-1b97-4233-baa9-a7e1cc54fae4">

2023-05-10 10:00 UTC, kvasyaa commented on db/migrate/20230509214343_create_employees.rb
> +      t.integer :id_number
the system creates `id` automatically.

2023-05-10 10:00 UTC, kvasyaa commented on test/fixtures/employees.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
use less file

2023-05-10 10:00 UTC, kvasyaa commented on test/models/employee_test.rb
> +
use less file

2023-05-10 10:00 UTC, kvasyaa commented on app/models/employee.rb
> +  def date_of_birth_not_younger_than_15_years
this method can be private

2023-05-10 11:03 UTC, DadaLV commented on db/migrate/20230509214343_create_employees.rb
> +      t.integer :id_number
so we don't need to write "табельний номер" ? should I delete it? I can't understand

2023-05-10 12:59 UTC, kvasyaa commented on db/migrate/20230509214343_create_employees.rb
> +      t.integer :id_number
`id` - will be a unique number

2023-05-10 13:02 UTC, vasyl-kvasnitsa requested changes

2023-05-10 13:02 UTC, vasyl-kvasnitsa commented on app/models/employee.rb
> +  validates :middle_name, presence: true, allow_blank: true, length: {minimum: 2, maximum: 30}
Chose `presence: true` or `allow_black: true`, but not both.

2023-05-15 10:28 UTC, vasyl-kvasnitsa approved these changes

2023-05-15 12:16 UTC, merged